#!/bin/sh

# Linker scripts, C files and headers
for i in `find -name *.h -or -name *.c -or -name *.ld`; do
	scripts/copyright_header -t c $i || scripts/copyright_header -u -t c $i
done

# Assembly files and include files
for i in `find -name *.asm -or -name *.inc`; do
	scripts/copyright_header -t nasm $i || scripts/copyright_header -u -t nasm $i
done
